
let container_1 = document.createElement('div');
let name1 = document.createElement('h3');
let age1 = document.createElement('p');
let img_1 = document.createElement('img');
let content_name1 = document.createTextNode('Ahmed');
let content_age1 = document.createTextNode('18 years old');
name1.appendChild(content_name1);
age1.appendChild(content_age1);
img_1.src = 'banner13.jpg';
container_1.appendChild(name1);
container_1.appendChild(age1);
container_1.appendChild(img_1);
document.body.appendChild(container_1);
img_1.style.width = '200px';
img_1.style.height = '200px';
container_1.style.width = '250px';
container_1.style.height = '150px';
container_1.style.paddingBottom = '200px';
container_1.style.marginLeft = '20px';
container_1.style.textAlign = 'center';
container_1.style.backgroundColor = '#444';
name1.style.paddingTop = '40px';
let container_2 = document.createElement('div');
let name2 = document.createElement('h3');
let age2 = document.createElement('p');
let img_2 = document.createElement('img');
let content_name2 = document.createTextNode('Ali');
let content_age2 = document.createTextNode('21 years old');
name2.appendChild(content_name2);
age2.appendChild(content_age2);
img_2.src = 'banner13.jpg';
container_2.appendChild(name2);
container_2.appendChild(age2);
container_2.appendChild(img_2);
document.body.appendChild(container_2);
img_2.style.width = '200px';
img_2.style.height = '200px';
container_2.style.width = '250px';
container_2.style.height = '150px';
container_2.style.paddingBottom = '200px';
container_2.style.marginLeft = '5px';
container_2.style.textAlign = 'center';
container_2.style.backgroundColor = '#444';
name2.style.paddingTop = '40px';

let container_3 = document.createElement('div');
let name3 = document.createElement('h3');
let age3 = document.createElement('p');
let img_3 = document.createElement('img');
let content_name3 = document.createTextNode('gamal');
let content_age3 = document.createTextNode('20 years old');
name3.appendChild(content_name3);
age3.appendChild(content_age3);
img_3.src = 'banner13.jpg';
container_3.appendChild(name3);
container_3.appendChild(age3);
container_3.appendChild(img_3);
document.body.appendChild(container_3);
img_3.style.width = '200px';
img_3.style.height = '200px';
container_3.style.width = '250px';
container_3.style.height = '150px';
container_3.style.paddingBottom = '200px';
container_3.style.marginLeft = '20px';
container_3.style.textAlign = 'center';
container_3.style.backgroundColor = '#444';
name3.style.paddingTop = '40px';
let container_4 = document.createElement('div');
let name4 = document.createElement('h3');
let age4 = document.createElement('p');
let img_4 = document.createElement('img');
let content_name4 = document.createTextNode('abderahmane');
let content_age4 = document.createTextNode('38 years old');
name4.appendChild(content_name4);
age4.appendChild(content_age4);
img_4.src = 'banner13.jpg';
container_4.appendChild(name4);
container_4.appendChild(age4);
container_4.appendChild(img_4);
document.body.appendChild(container_2);
img_4.style.width = '200px';
img_4.style.height = '200px';
container_4.style.width = '250px';
container_4.style.height = '150px';
container_4.style.paddingBottom = '200px';
container_4.style.marginLeft = '5px';
container_4.style.textAlign = 'center';
container_4.style.backgroundColor = '#444';
name4.style.paddingTop = '40px';
let global_container_1 = document.createElement('div');
global_container_1.appendChild(container_1);
global_container_1.appendChild(container_3);
document.body.appendChild(global_container_1);
global_container_1.style.display = 'inline-block';
let global_container_2 = document.createElement('div');
global_container_2.appendChild(container_2);
global_container_2.appendChild(container_4);
document.body.appendChild(global_container_2);
global_container_2.style.display = 'inline-block';
